### ISSUE TITLE
Axios wrapper

### ISSUE THREAD

**Issue by Franinowa** [esparciapps/base-laravel-vue#32]
Wrap axios in an api object and control all the http calls from there, through modules.

**Comment by Noogic** [comment]
### Responsibilities/Features
- Wrap the external library to make http calls (i.e. axios)
- Handle the routes' resources
- Coordinate 

### Proposal
- Create the **Http** class/object as requester wrapper, which will implement basic methods like *get*, *post*, *put*, *patch* and *delete* but also will offer more verbose methods like *find*, *all*, *index*, *create*, *update* or *destroy*.
> This class will require a *requester* object (axios) and a *resource routes* object.
- Create the **Resource Router** class/object, which will give the routes for the declared resources.
> The router must accept both the resources and single routes and should accept an alias for both of them.
